// <auto-generated />
namespace Passion_Project_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class manufactrerPic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manufactrerPic));
        
        string IMigrationMetadata.Id
        {
            get { return "202106240226172_manufactrerPic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
