// <auto-generated />
namespace Passion_Project_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class aircraftmanufacturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aircraftmanufacturer));
        
        string IMigrationMetadata.Id
        {
            get { return "202105301630500_aircraft-manufacturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
